### ISSUE TITLE
Add bower_components to your .gitignore

### ISSUE THREAD

**Issue by msmichellegar** [smooth-operators-fac/currency-map#24] opened 2016-06-24 11:39 UTC
You have pushed Jasmine core to GitHub, which is probably unnecessary and impacts the tidiness of the repo. I'd remove it from GitHub and add `bower_components` to your `.gitignore` file. Just make sure you tell people to install Jasmine with Bower before running the tests in your project run instructions.

Michelle

**Comment by g-sam** [comment] 2016-06-24 12:14
.gitignore updated. will register with next commit

**Comment by msmichellegar** [comment] 2016-06-24 12:37
👍

Let me know when you've merged the commit to master, and I'll close the issue!

**Comment by g-sam** [comment] 2016-06-25 17:30
Merged.

**Comment by msmichellegar** [comment] 2016-06-26 13:26
Actually, on review it looks like you added the bower config file to the .gitignore rather than the actual bower_components. You _will_ need the bower config file on GitHub, just not the actual bower modules/components like Jasmine since those are on your local machine, and clutter up the repo.

Will reopen, but I know the week is over now so depends on if you still want to fix ;)

**Comment by daymos** [comment] 2016-06-26 16:26
Hi Michelle, so the problem is that we used a generator to set up the testing environment. And the generator was using bower to run some task. I have tried to make an npm package but the issue is that if the generator is run again it will also create a new test folder and cancel our code. And I tried to install bower and have it set up Jasmine dependancies, but the paths are different so the user would need to change them in the html. So in practice we don't know what to do :)

**Comment by g-sam** [comment] 2016-06-27 09:24
What if the user installed jasmine with generator-jasmine then did

```
git pull -Xtheirs origin master
```

ok there must be a better way.

**Comment by daymos** [comment] 2016-06-27 10:25
what os the -X option?
I think It would be a good case to create a generator ourselves and release it on npm

**Comment by g-sam** [comment] 2016-06-27 11:58
Resolves all merge conflicts by preferring whatever is in the uncheckedout branch ('their' one. can also do reverse with 'ours').
Actually I think should be `git pull -Xtheirs origin master` (no space), according to [this](http://miguelcamba.com/blog/2013/04/24/git-tip-merge-branches-taking-always-changes-from-one-of-them/)

**Comment by msmichellegar** [comment] 2016-06-27 12:19
You people are so on it! Will take a look when I have a chance :)

**Closed as completed** 2016-07-06 15:41 UTC
